let allAnswers = 
// {
//     GSA_Involvement: "",
//     GSA_Association: "",
//     Values_1: "",
//     Values_2: "",
//     Values_3: "",
//     Values_4: "",
//     Values_5: "",
//     Values_6: "",
//     Values_7: "",
//     Values_8: "",
//     Values_9: "",
//     Scenarios_1: "",
//     Scenarios_2: "",
//     Scenarios_3: "",
//     Scenarios_4: "",
//     Open_1: "",
//     Open_2: "",
//     Open_3: "",
//     Open_4: "",
//     Open_5: "",
//     Hope: "",
//     Fear: "",
// };

    {
        "GSA_Involvement": "NA",
        "GSA_Association": [
          "NA"
        ],
        "Values_1": "NA",
        "Values_2": "NA",
        "Values_3": "NA",
        "Values_4": "NA",
        "Values_5": "NA",
        "Values_6": "NA",
        "Values_7": "NA",
        "Values_8": "NA",
        "Values_9": "NA",
        "Scenarios_1": "NA",
        "Scenarios_2": "NA",
        "Scenarios_3": "NA",
        "Scenarios_4": "NA",
        "Open_1": "NA",
        "Open_2": "NA",
        "Open_3": "NA",
        "Open_4": "NA",
        "Open_5": "NA",
        "Hope": "NA",
        "Fear": "NA"
      }
