let allAnswers = 
// {
//     GSA_Involvement: "",
//     GSA_Association: "",
//     Values_1: "",
//     Values_2: "",
//     Values_3: "",
//     Values_4: "",
//     Values_5: "",
//     Values_6: "",
//     Values_7: "",
//     Values_8: "",
//     Values_9: "",
//     Scenarios_1: "",
//     Scenarios_2: "",
//     Scenarios_3: "",
//     Scenarios_4: "",
//     Open_1: "",
//     Open_2: "",
//     Open_3: "",
//     Open_4: "",
//     Open_5: "",
//     Hope: "",
//     Fear: "",
// };

    {
        "GSA_Involvement": "Staff",
        "GSA_Association": [
          "Architecture"
        ],
        "Values_1": "Your Art School believes completely in raw creativity.",
        "Values_2": "Your Art School believes completely in stand alone disciplines.",
        "Values_3": "Your Art School believes completely it’s role is to critique from the outside.",
        "Values_4": "Students at your Art School are completely kick-starting a career.",
        "Values_5": "Students at your Art School are completely ‘Jack of all trades’.",
        "Values_6": "Students at your Art School are completely following a set curriculum.",
        "Values_7": "Your Art School is completely focusing on improving digital resources.",
        "Values_8": "Your Art School is completely for people all over the world.",
        "Values_9": "Your Art School is completely historic and prestigious.",
        "Scenarios_1": "When your Art School is losing money, you completely ask for donations.",
        "Scenarios_2": "To improve your campus, you completely improve existing space.",
        "Scenarios_3": "With an increased appetite for digital learning, you completely use digital learning to teach a diverse range of students around the world.",
        "Scenarios_4": "Your admissions process is completely open to all, with big student cohorts.",
        "Open_1": "I would make an international call for more artists to come and live here as part of the plan to make the area a world centre for art.",
        "Open_2": "The creative industries are the future and only a very small % of the population is equipped to work in them. Art school equips people with the skills they need to compete in the creative industries of the future.",
        "Open_3": "I would make an international call for more artists to come and live here as part of the plan to make the area a world centre for art.",
        "Open_4": "The creative industries are the future and only a very small % of the population is equipped to work in them. Art school equips people with the skills they need to compete in the creative industries of the future.",
        "Open_5": "I would make an international call for more artists to come and live here as part of the plan to make the area a world centre for art.",
        "Hope": "",
        "Fear": ""
      }
