let AllQuestions = [
    [
        3,
        "Your future Art School has...",
        "A big student population",
        "A small student population",
        "Your future Art School has",
        "a big student population",
        "a small student population",
        "believe Art School should",
        "have big student populations.",
        "have small student populations."
    ],
    [
        4,
        "Your future Art School believes...",
        "In stand-alone disciplines",
        "In interdisciplinarity",
        "Your future Art School believes",
        "in stand-alone disciplines",
        "in interdisciplinarity",
        "believe Art School should",
        "have stand-alone disciplines. ",
        "be interdisciplinary. "
    ],
    [
        5,
        "Students at your future Art School are...",
        "Kick-starting a career",
        "Learning throughout a lifetime",
        "Students at your future Art School are",
        "kick-starting a career",
        "learning throughout a lifetime",
        "believe Art School students should be",
        "kick-starting a career.",
        "learning throughout a lifetime."
    ],
    [
        6,
        "Students at your future Art School are...",
        "Following a set curriculum",
        "Building their own curriculum",
        "Students at your future Art School are",
        "following a set curriculum",
        "building their own curriculum",
        "believe Art School students should",
        "follow a set curriculum.",
        "build their own curriculum. "
    ],
    [
        7,
        "Staff at your future Art School are…  ",
        "Part-time whilst developing their own practice",
        "Full-time academics",
        "Staff at your future Art School are  ",
        "part-time whilst developing their own practice",
        "full-time academics",
        "believe Art School staff should be",
        "part-time whilst developing their own practice.",
        "full-time academics."
    ],
    [
        8,
        "Your future Art School is…",
        "Prioritising formal teaching",
        "Prioritising peer learning",
        "Your future Art School is",
        "prioritising formal teaching",
        "prioritising peer learning",
        "believe Art School should",
        "prioritise formal teaching.",
        "prioritise peer learning. "
    ],
    [
        9,
        "Your future Art School is...",
        "Prioritising online learning",
        "Prioritising in-person learning",
        "Your future Art School is",
        "prioritising online learning",
        "prioritising in-person learning",
        "believe Art School should",
        "prioritise online learning.",
        "prioritise in-person learning."
    ],
    [
        10,
        "Your future Art School is...",
        "All over the world",
        "Embedded in one place",
        "Your future Art School is",
        "all over the world",
        "embedded in one place",
        "believe Art School should be",
        "global. ",
        "place-based. "
    ],
    [
        11,
        "Your future Art School is...",
        "Historic and traditional",
        "Emergent and dynamic",
        "Your future Art School is",
        "historic and traditional",
        "emergent and dynamic",
        "believe Art School should be",
        "historic and traditional.",
        "emergent and dynamic. "
    ],
    [
        12,
        "Your Art School has identified widening participation as a key priority area. Do you...",
        "Maintain the current course structures but increase the availability of financial support",
        "Introduce more flexible part-time and distance learning options",
        "You approach widening participation by",
        "maintaining the current course structures but increasing the availability of financial support.",
        "introducing more flexible part-time and distance learning options. ",
        "said they would approach widening participation by",
        "maintaining the current course structures but increasing the availability of financial support.",
        "introducing more flexible part-time and distance learning options. "
    ],
    [
        13,
        "You wish to improve diversity at your future Art School. Do you… ",
        "Prioritise support for a more diverse student population",
        "Prioritise constructing a decolonial curriculum",
        "To improve diversity you prioritise",
        "supporting a more diverse student population.",
        "constructing a decolonial curriculum.",
        "said they would prioritise",
        "supporting a more diverse student population.",
        "constructing a decolonial curriculum."
    ],
    [
        14,
        "You want your future Art School to give students opportunities to work on projects with external partners. Do you...",
        "Curate a limited number of large institutional partnerships",
        "Enable many smaller, locally sourced and negotiated projects",
        "You offer students the opportunity to work with external partners by",
        "curating a limited number of large institutional partnerships.",
        "enabling many smaller, locally sourced and negotiated projects.",
        "said they would",
        "curate a limited number of large institutional partnerships.",
        "enable many smaller, locally sourced and negotiated projects."
    ],
    [
        15,
        "Your future art school wants to develop new areas of academic excellence. Do you...",
        "Hire several early-career academics to develop them and build a reputation over time",
        "Hire a small number of leading discipline specialists to develop them more quickly",
        "In order to develop new areas of academic excellence, you decide to",
        "hire several early-career academics to develop them and build a reputation over time.",
        "hire a small number of leading discipline specialists to develop them more quickly.",
        "said they would",
        "hire several early-career academics to develop them and build a reputation over time.",
        "hire a small number of leading discipline specialists to develop them more quickly."
    ]
];

let OpenQuestions = [
    "I want my future Art School to be known for...",
    "In my first 100 days leading my future Art School, I would…",
    "My future Art School will nurture…",
    "My future Art School will provide students with the following added value once they graduate…",
    "My future Art School will attract staff to work at it by…",
];

let OpenAnswers = [
    [
        "High quality of the learning experience, and being a truly diverse and inclusive institution.",
        "ground breaking forward thinking work and invention",
        "Challenging the status quo, encouraging multiple approaches to learning and having excellent teaching staff and facilities",
        "Creating world renowned quality artists and designers with unique design flare and integrity",
        "Its commitment to equality, diversity, and inclusion through creativity.",
        "Quality of curriculum, Independent thinkers (graduates), creative graduates across the globe",
        "Pushing boundaries, comprehensive (interdisciplinary) courses and world class teachers",
        "Emergence and Flexibility",
        "student engagement and interaction, providing resource and opportunity, equipping students with knowledge, and a practical and theoretical skillset",
        "Being an inclusive place embedded in its community where people can learn with and from other practitioners across a variety of skills and interests",
        "collaboration, progressive thinking, high standard of graduates and functionality. ",
        "developing creative, critical and ethical thinker-makers.",
        "Great links with industry and world leading applicable skills",
        "Diversity and flexibility with its learning. Considering year groups which are mixed and projects and the course are focussed towards the part-time staff's skillset - consider electives to build learning rather than rigid course structures.",
        "enabling student learning in an atmosphere of trust, openness and mutual respect. Academics given real agency alongside responsibility. Hierarchy challenged constructively and risk and failure welcomed and understood, not feared and forgotten about. ",
        "Innovation and inclusion. My art school would embed itself in the poorest communities in Glasgow and work to improve outcomes by offering out-of-hours courses and opportunites for local businesses to grow and residents to thrive. ",
        "Larger student populations, filled with diverse artists, but SMALL, intimate classes that value connection in a non-hierarchical way. Strong, seamless integration between academic and technical staff that sets a standard for team work, collaboration, and mutual respect.",
        "nurturing talent focused on students and not being a money-making machine that exhausts both students and staff. It would be great if the institution would be a unified entity and not a division between institutional structure-bureaucracy vs staff-student community."
    ],
    [
        "Trial a new interdisciplinary programme, develop new partnerships with civic organisations and set up residencies for students in and around the city.",
        "Establish good wellbeing services for staff and students, and build the school system to nurture sustainability and post colonial education around flexible course structures.",
        "Evolve organisational structure to create flatter hierarchies  - an Art School that is governed first and foremost by those involved in teaching and learning. ",
        "Speak to as many students as possible",
        "Get to know the team working there, the students, the key stakeholders. Assess where the School has been, where it is going and conduct a gap analysis. Understand the priorities for the immediate future, middle and longer term. Start to create a supportive, inclusive culture",
        "Make sure the students feel safe in their school environment to have optimal chances to progress.",
        "provide outdoor working spaces, create communal meeting spaces, exhibition spaces, a cafe, a student union, re-allocate admin staff to departments - put the soul back into GSA.",
        "Listen, listen, listen. Then ask some questions: What's already working well, where could resources be directed to build on this? What are we missing? Who's 'we' in this context? What's right for the GSA community (even if this is at odds with what other institutions are doing)?",
        "Ensure all students have a dedicated space for study and work, develop new opportunities for collaboration across disciplines",
        "Attempt to discover the strengths and weaknesses of existing staff and provide the necessary encouragement and facilities for them to, in turn, inspire the best possible work from the students. Find new staff to reinforce existing practices and develop new areas of expertise. ",
        "Remove the barriers between staff and management",
        "increase transparency and the goals of the curriculum so students are aware of and feel confident in what theyre learning.",
        "Have a compulsory whole-school fancy dress party so we remember why we love being creative and showing off. Invest in administration digital infrastructure so staff can spend more time being creative and less time trying to find information and data. Committ to rebuilding the Mac",
        "Provide teaching staff with better woking and income conditions. Much greater racial and social class diversity amongst student and staff body. More skills based teaching",
        "Resign as director and create a more horizontal staff structure that gives greater autonomy to teachers and students.",
        "Ask Alumni what they wished GSA had provided, sense check against the now and current student ambitions.",
        "Quantify all of the teaching resources both academcs and their courses. Match programme to premise. Work with staff to determine direction of the school. Gather information from and visit all discplines. Put together timetable for all agreed goals. Liaise with industry partners.",
        "Re-evaluate financial structures that rely on international students above the quality of education. Reduce middle management and connect directly with student-facing staff to learn about (and ACT on) their feedback and suggestions."
    ],
    [
        "Pragmatism - students will learn to engage people across society, meeting people where they are, and understanding how best to make impact.",
        "An understanding and a connection to the society they live in through creative practices",
        "Be self-reflexive practitioners and socially conscious thinkers, learning collaboratively through engaging with ideas, materials, people and place.",
        "A mixture of thought process and skill",
        "Inclusiveness, diversity, respect, equality, creativity, interdisciplinarity, collaboration, cohesion, trust.",
        "interdisciplinary practices",
        "learning through doing, through shared experience, through building community.",
        "Students and staff alike to ask creative questions that no one else is asking, in relation to the planet and humanity and how creativity can help support the planet and its inhabitants.",
        "Sustainability, the city of Glasgow and the creative talents that pass through. It will also nuture the staff that work in it, helping to keep it as a much-loved place of employment and creativity.",
        "Principles, ethics, a holistic approach to everything creativity-related, showing-instead-of-telling how art and design are ONE with politics and what's going on in the world. Responsibilising & empowering students and becoming accessible (ESP. financially) to those marginalized.",
        "..people not processes focussing on the growth of the individual and resist the bullying of 'quality assurance'",
        "Practical making, critical thinking,  class, race and gender equality. ",
        "Experimentation, craftsmanship, and innovative ideas and approaches. It will foster connection, belonging and a sense of family amongst staff and students. Equality (diversity, respect, self-governance for staff and students and recognition).",
        "learners. simply that. it would centre entirely on independent learners, encouraging and enabling their agency, and their engagement with and enjoyment of the process of learning. i think a good art school is really a simple thing, and everything has got waaay too complicated.",
        "Individual expression and growth, life-long peer-support by developing critical friends within the schools",
        "a diverse body of students who are socially and ethically aware practitioners and innovative interdisciplinary practices",
        "A healthy work culture",
        "Internal and external collaboration"
    ],
    [
        "Students will not only have had a space to develop critical thinking and craft, but they will also have experience of working with a range of third party orgs — they will be contextually aware, and able to understand the value of their work.",
        "Throughout the time in study students have had the opportunity to partner with organisations - either self organised or planned on small scale - and therefore have a level of confidence in what they want to do and where they want to go next",
        "Access to resources (libraries, workshops, studio space) that supports sharing of knowledge, skills and initiating projects with others. Enabling a self-organised, peer-led model of education. ",
        "the ability to apply creativity in a variety of ways",
        "Confidence and professional opportunities",
        "Before graduation, make the students aware of the massive challenges in being an artist and making a living. With money for arts dwindling there is a need for a reality check from day one. My art school would not be making charity applicants",
        "The ability to respond critically to challenges and make a practical impact to people's lives. ",
        "confidence to engage with others in an ethical and socially responsible way. Agency to take the initiative and create opportunities using imagination and hard work.",
        "An Alumni that is like an extended family.",
        "Unstoppable curiosity, a care-ful approach, the ability to really focus and concentrate, to seek insights, to be responsive and comfortable in uncertainty, to have the skills and networks to sustain themselves and to thrive as they move through their career.",
        "closing the gap between study and work so you won't disapire in the blackhole of unemployed artgraduate life.",
        "A strong set of practical and analytical skills they will use in the workplace, a wide creative network",
        "An active, cross-disciplinary network of alumni, access to the school's resources even after graduation, mentoring, and first-access opportunities in the local context for those who wish to give back : ) ",
        "A strong appreciation of the environment in which they live. To feel useful.",
        "Ethical and compassionate practices",
        "they will have a keen sense of how to invent, contrive and develop ideas as maker-thinkers",
        "a rejection of cumulative notions such as 'added value' as reproductive of given ways of working in art that continue to exclude marginalised and oppressed community.",
        " of being self sufficient with skills like drawing at the core, plus those disciplinary skills from the chosen department that prepares the person for a lifelong career. The place will be associated with academic excellence, innovation, inclusion not the fires or painting"
    ],
    [
        "Being a melting pot. There will be no full time teaching staff — all staff will be practising. Staff will be attracted by the network of other staff members, and the opportunity to share and learn from each other.",
        "The opportunity to share knowledge and learn at the same time. Staff have the time to practice and develop their practice in the side either within or outwith the school. The hierarchy between staff and students would be reduced due to the varied demographic of the student body.",
        "Time, resource and agency to develop their practise. Participants of the school are both learners and teachers. ",
        "Being forward thinking and considerate of its staff, their skills and their time.",
        "Being known as a place people want to work at due to its reputation. Innovative, dynamic",
        "promoting diversity amongst them",
        "providing access to transparent job progression pathways",
        "Taking away the job of social workers for immature young adults. 50% of staff would be on visiting assignments, 20% of my own staff would be away on exchange assignment for 2 years +",
        "Increasing peer networks within areas of specialist expertise",
        "A sense of community, shared purpose, a feeling of participating directly in shaping the cultural landscape of the city and Scotland. Asking staff to be critical and always up-to-date in their field, without risking to be \"too challenging\" for the establishment. Eg. decolonising.",
        "Good salaries and space to do their own work as well as teach.",
        "actually being/doing the things it often says it does, but isn't. there is a cognitive dissonance when an organisation claims to be creative, disruptive, innovative etc, but its working environment, practices, procedures etc are leaden, unresponsive, disempowering and exhausting.",
        "ensuring good working conditions, fair pay, reasonable workloads and good amounts of contact time with students. ",
        "Offering excellent research and career development support, as well as empowering teaching staff through having greater influence on curriculum development and application of resources.  ",
        "competitive pay and flexible working patterns",
        "....genuinely valuing the staff experience, cliche but academics generally don't do it for the money particularly the part-time staff who comprise the majority of academics....find out what makes them tick.",
        "Having a structure that supports reflection, personal practice and collaboration in order to enrich programmes and courses",
        "its air of possibility, freedom and challenge; its links with current debates and work world wide--and the evidence that anybody will be encouraged start to put their ideas into practice"
    ]
];
