let AllQuestions = [
    [
        3,
        "Your future Art School has...",
        "A big student population",
        "A small student population",
        "Your future Art School has",
        "a big student population",
        "a small student population",
        "believe Art School should",
        "have big student populations.",
        "have small student populations.",
    ],
    [
        4,
        "Your future Art School believes...",
        "In stand-alone disciplines",
        "In interdisciplinarity",
        "Your future Art School believes",
        "in stand-alone disciplines",
        "in interdisciplinarity",
        "believe Art School should ",
        "have stand-alone disciplines. ",
        "be interdisciplinary. ",
    ],
    [
        5,
        "Students at your future Art School are...",
        "Kick-starting a career",
        "Learning throughout a lifetime",
        "Students at your future Art School are",
        "kick-starting a career",
        "learning throughout a lifetime",
        "believe Art School students should be",
        "kick-starting a career.",
        "learning throughout a lifetime.",
    ],
    [
        6,
        "Students at your future Art School are...",
        "Following a set curriculum",
        "Building their own curriculum",
        "Students at your future Art School are",
        "following a set curriculum",
        "building their own curriculum",
        "believe Art School students should ",
        "follow a set curriculum.",
        "build their own curriculum. ",
    ],
    [
        7,
        "Staff at your future Art School are…  ",
        "Part-time whilst developing their own practice",
        "Full-time academics",
        "Staff at your future Art School are  ",
        "part-time whilst developing their own practice",
        "full-time academics",
        "believe Art School staff should be",
        "part-time whilst developing their own practice.",
        "full-time academics.",
    ],
    [
        8,
        "Your future Art School is…",
        "Prioritising formal teaching",
        "Prioritising peer learning",
        "Your future Art School is",
        "prioritising formal teaching",
        "prioritising peer learning",
        "believe Art School should ",
        "prioritise formal teaching.",
        "prioritise peer learning. ",
    ],
    [
        9,
        "Your future Art School is...",
        "Prioritising online learning",
        "Prioritising in-person learning",
        "Your future Art School is",
        "prioritising online learning",
        "prioritising in-person learning",
        "believe Art School should ",
        "prioritise online learning.",
        "prioritise in-person learning.",
    ],
    [
        10,
        "Your future Art School is...",
        "All over the world",
        "Embedded in one place",
        "Your future Art School is",
        "all over the world",
        "embedded in one place",
        "believe Art School should be ",
        "global. ",
        "place-based. ",
    ],
    [
        11,
        "Your future Art School is...",
        "Historic and traditional",
        "Emergent and dynamic",
        "Your future Art School is",
        "historic and traditional",
        "emergent and dynamic",
        "believe Art School should be ",
        "historic and traditional.",
        "emergent and dynamic. ",
    ],
    [
        12,
        "Your Art School has identified widening participation as a key priority area. Do you...",
        "Maintain the current course structures but increase the availability of financial support",
        "Introduce more flexible part-time and distance learning options ",
        "You approach widening participation by ",
        "maintaining the current course structures but increasing the availability of financial support.",
        "introducing more flexible part-time and distance learning options. ",
        "said they would approach widening participation by",
        "maintaining the current course structures but increasing the availability of financial support.",
        "introducing more flexible part-time and distance learning options. ",
    ],
    [
        13,
        "You wish to improve diversity at your future Art School. Do you… ",
        "Prioritise support for a more diverse student population",
        "Prioritise constructing a decolonial curriculum",
        "To improve diversity you prioritise ",
        "supporting a more diverse student population.",
        "constructing a decolonial curriculum.",
        "said they would prioritise ",
        "supporting a more diverse student population.",
        "constructing a decolonial curriculum.",
    ],
    [
        14,
        "You want your future Art School to give students the best opportunities to work on projects with external partners. Do you...",
        "Curate a limited number of large institutional partnerships",
        "Enable many smaller, locally sourced and negotiated projects",
        "You offer students the opportunity to work with external partners by ",
        "curating a limited number of large institutional partnerships.",
        "enabling many smaller, locally sourced and negotiated projects.",
        "said they would ",
        "curate a limited number of large institutional partnerships.",
        "enable many smaller, locally sourced and negotiated projects.",
    ],
    [
        15,
        "Your future art school wants to develop new areas of academic excellence. Do you...",
        "Hire several early-career academics to develop them and build a reputation over time",
        "Hire a small number of leading discipline specialists to develop them more quickly",
        "In order to develop new areas of academic excellence, you decide to ",
        "hire several early-career academics to develop them and build a reputation over time.",
        "hire a small number of leading discipline specialists to develop them more quickly.",
        "said they would ",
        "hire several early-career academics to develop them and build a reputation over time.",
        "hire a small number of leading discipline specialists to develop them more quickly.",
    ],
];

let OpenQuestions = [
    "I want my future Art School to be known for...",
    "In my first 100 days leading my future Art School, I would…",
    "My future Art School will nurture…",
    "My future Art School will provide students with the following added value once they graduate…",
    "My future Art School will attract staff to work at it by…",
];

let OpenAnswers = [
    [
        "High quality of the learning experience, and being a truly diverse and inclusive institution.",
        "ground breaking forward thinking work and invention",
        "Challenging the status quo, encouraging multiple approaches to learning and having excellent teaching staff and facilities",
        "Creating world renowned quality artists and designers with unique design flare and integrity",
        "Its commitment to equality, diversity, and inclusion through creativity.",
        "Quality of curriculum, Independent thinkers (graduates), creative graduates across the globe",
        "Pushing boundaries, comprehensive (interdisciplinary) courses and world class teachers",
        "Emergence and Flexibility",
        "student engagement and interaction, providing resource and opportunity, equipping students with knowledge, and a practical and theoretical skillset",
        "Being an inclusive place embedded in its community where people can learn with and from other practitioners across a variety of skills and interests",
        "collaboration, progressive thinking, high standard of graduates and functionality. ",
        "developing creative, critical and ethical thinker-makers.",
    ],
    [
        "always outward",
        "Working together, questioning everything, helping us all",
        "GSA a community for the worlds best creative minds",
        "To capitalise upon a students existing knowledge alongside providing opportunities to make interdisciplinary collaborations to create dynamic graduates that would be ready to enter the design market",
        "Fuck the default",
        "Change mindsets, change action",
        "equipping students with confidence in their own practice and the ability to utilise what they have learned",
        "Changing Conventions ",
    ],
];
